services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - ./migrations/up:/docker-entrypoint-initdb.d
      - abroad-payroll-api:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    environment:
      - APP_PORT=3030
      - DB_URL=postgres://postgres:123456@postgres:5432/postgres
      - JWT_SECRET=123456
    volumes:
      - ./:/app

volumes:
  abroad-payroll-api:
