services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: api
    volumes:
      - ./migrations/up:/docker-entrypoint-initdb.d
      - abroad-payroll-api:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    environment:
      - APP_PORT=3030
      - DB_URL=postgres://postgres:123456@postgres:5432/api
      - JWT_SECRET=123456
    volumes:
      - ./:/app

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: 123456
      MB_DB_HOST: postgres

volumes:
  abroad-payroll-api:
